server:
  port: 8089

spring:
  application:
    name: backtest-svc

marketdata:
  url: ${MARKET_DATA_URL:http://localhost:8087}

analysis:
  url: ${ANALYSIS_URL:http://localhost:8088}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
