import React from 'react';
import { compareBacktests, getAnalysisHistory, getBacktestStrategies, runBacktest, runModelReplay } from '../lib/platform';

export default function BacktestingPage({ activeSymbol }) {
  const [strategies, setStrategies] = React.useState([]);
  const [selectedStrategy, setSelectedStrategy] = React.useState('SMA_CROSSOVER');
  const [backtest, setBacktest] = React.useState(null);
  const [comparison, setComparison] = React.useState(null);
  const [history, setHistory] = React.useState([]);
  const [modelReplay, setModelReplay] = React.useState(null);
  const [capital, setCapital] = React.useState('100000');
  const [positionPct, setPositionPct] = React.useState('0.95');
  const [commission, setCommission] = React.useState('1.0');
  const [slippage, setSlippage] = React.useState('5');
  const [allowShort, setAllowShort] = React.useState(true);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState(null);

  const load = React.useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const [strategyData, historyData, comparisonData] = await Promise.all([
        getBacktestStrategies(),
        getAnalysisHistory(activeSymbol),
        compareBacktests({ symbol: activeSymbol }),
      ]);
      setStrategies(strategyData || []);
      setHistory(historyData || []);
      setComparison(comparisonData || null);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }, [activeSymbol]);

  React.useEffect(() => {
    load();
  }, [load]);

  const handleRun = async () => {
    setError(null);
    try {
      const result = await runBacktest({
        symbol: activeSymbol,
        strategy: selectedStrategy,
        capital: Number(capital),
        positionPct: Number(positionPct),
        commission: Number(commission),
        slippage: Number(slippage),
      });
      setBacktest(result);
    } catch (e) {
      setError(e.message);
    }
  };

  const handleModelReplay = async () => {
    setError(null);
    try {
      const result = await runModelReplay({
        symbol: activeSymbol,
        capital: Number(capital),
        positionPct: Number(positionPct),
        commission: Number(commission),
        slippage: Number(slippage),
        allowShort,
      });
      setModelReplay(result);
    } catch (e) {
      setError(e.message);
    }
  };

  return (
    <main className="page-grid page-grid-2">
      <section className="panel page-span-2">
        <div className="panel-header justify-between">
          <div className="flex items-center gap-3">
            <div className="dot" />
            Backtesting lab
          </div>
          <div className="flex gap-2 flex-wrap">
            <span className="metric-chip">{activeSymbol}</span>
            <button className="btn btn-ghost" onClick={load} disabled={loading}>Refresh</button>
          </div>
        </div>
        <div className="card-body">
          <p className="spark-note">
            This page connects the historical strategy engine with the live analysis system. You can run a strategy,
            compare built-in strategies, and review the persisted model/rule recommendations generated by `analysis-svc`.
          </p>
        </div>
      </section>

      <section className="panel">
        <div className="panel-header">
          <div className="dot" />
          Run a backtest
        </div>
        <div className="card-body space-y-4">
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="label">Capital</label>
              <input value={capital} onChange={(e) => setCapital(e.target.value)} />
            </div>
            <div>
              <label className="label">Position %</label>
              <input value={positionPct} onChange={(e) => setPositionPct(e.target.value)} />
            </div>
            <div>
              <label className="label">Commission</label>
              <input value={commission} onChange={(e) => setCommission(e.target.value)} />
            </div>
            <div>
              <label className="label">Slippage (bps)</label>
              <input value={slippage} onChange={(e) => setSlippage(e.target.value)} />
            </div>
          </div>
          <label className="pill" style={{ width: 'fit-content', cursor: 'pointer' }}>
            <input type="checkbox" checked={allowShort} onChange={(e) => setAllowShort(e.target.checked)} style={{ width: 16 }} />
            Allow short replay
          </label>
          <div>
            <label className="label">Strategy</label>
            <select value={selectedStrategy} onChange={(e) => setSelectedStrategy(e.target.value)}>
              {strategies.map((strategy) => (
                <option key={strategy.id} value={strategy.id}>{strategy.name}</option>
              ))}
            </select>
          </div>
          <button className="btn btn-primary w-full" onClick={handleRun}>Run backtest</button>
          {backtest && (
            <div className="grid grid-cols-2 gap-3">
              <Metric label="Total return" value={`${backtest.totalPnlPct}%`} tone={Number(backtest.totalPnlPct) >= 0 ? 'positive' : 'negative'} />
              <Metric label="Sharpe" value={String(backtest.sharpeRatio)} tone="blue" />
              <Metric label="Max DD" value={`${backtest.maxDrawdownPct}%`} tone="negative" />
              <Metric label="Trades" value={String(backtest.totalTrades)} tone="accent" />
            </div>
          )}
          <button className="btn btn-ghost w-full" onClick={handleModelReplay}>Replay persisted model signals</button>
          {modelReplay && (
            <div className="grid grid-cols-2 gap-3">
              <Metric label="Model replay return" value={`${modelReplay.totalReturnPct}%`} tone={Number(modelReplay.totalReturnPct) >= 0 ? 'positive' : 'negative'} />
              <Metric label="Replay trades" value={String(modelReplay.tradeCount)} tone="blue" />
              <Metric label="Signal count" value={String(modelReplay.signalCount)} tone="accent" />
              <Metric label="Ending capital" value={`$${Number(modelReplay.endingCapital).toLocaleString('en-US')}`} tone="gold" />
              <Metric label="Final side" value={String(modelReplay.finalSide)} tone="blue" />
              <Metric label="Execution" value={`${modelReplay.commission} / ${modelReplay.slippageBps}bps`} tone="accent" />
              <Metric label="Shorting" value={modelReplay.allowShort ? 'Enabled' : 'Disabled'} tone="blue" />
            </div>
          )}
          {error && <div className="soft-block p-4 mono text-sm negative">{error}</div>}
        </div>
      </section>

      <section className="panel">
        <div className="panel-header">
          <div className="dot" />
          Strategy comparison
        </div>
        <div className="card-body">
          {comparison?.comparisons?.length ? (
            <div className="grid gap-3">
              {comparison.comparisons.map((item) => (
                <div key={item.strategy} className="soft-block p-4">
                  <div className="flex items-center justify-between gap-4">
                    <div>
                      <div className="summary-label">{item.strategy}</div>
                      <div className="mono text-lg">{item.totalReturn}% return</div>
                    </div>
                    <div className="mono text-sm neutral text-right">
                      <div>Sharpe {item.sharpe}</div>
                      <div>PF {item.profitFactor}</div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <p className="spark-note">{loading ? 'Loading strategy comparison...' : 'No comparison data available.'}</p>
          )}
        </div>
      </section>

      <section className="panel page-span-2">
        <div className="panel-header">
          <div className="dot" />
          Persisted signal history
        </div>
        <div className="table-head" style={{ gridTemplateColumns: '1fr 0.8fr 0.8fr 0.8fr 0.8fr 1.4fr' }}>
          <span>Timestamp</span>
          <span>Rule</span>
          <span>Model</span>
          <span>Blend</span>
          <span>Alignment</span>
          <span>Summary</span>
        </div>
        <div className="flex-1 overflow-y-auto min-h-0">
          {history.map((item) => (
            <div key={item.id} className="table-row" style={{ gridTemplateColumns: '1fr 0.8fr 0.8fr 0.8fr 0.8fr 1.4fr' }}>
              <span className="mono text-sm neutral">{new Date(item.createdAt).toLocaleString('en-US', { hour12: false })}</span>
              <span className={`mono text-sm ${toneForAction(item.ruleAction)}`}>{item.ruleAction}</span>
              <span className={`mono text-sm ${toneForAction(item.modelAction)}`}>{item.modelAction || 'N/A'}</span>
              <span className={`mono text-sm ${toneForAction(item.blendedAction)}`}>{item.blendedAction}</span>
              <span className="mono text-sm blue">{item.alignment}</span>
              <span className="mono text-sm neutral">{item.summary}</span>
            </div>
          ))}
          {!history.length && (
            <div className="h-full flex items-center justify-center p-8 text-center">
              <p className="spark-note">{loading ? 'Loading signal history...' : 'No signal history yet. Visit the analysis page to generate suggestions.'}</p>
            </div>
          )}
        </div>
      </section>

      <section className="panel page-span-2">
        <div className="panel-header">
          <div className="dot" />
          Replay structure events
        </div>
        <div className="table-head" style={{ gridTemplateColumns: '1fr 0.8fr 1fr 1fr' }}>
          <span>Date</span>
          <span>Event</span>
          <span>Level / zone</span>
          <span>Context</span>
        </div>
        <div className="flex-1 overflow-y-auto min-h-0">
          {(modelReplay?.replayEvents || []).map((item, index) => (
            <div key={`${item.date}-${item.event}-${index}`} className="table-row" style={{ gridTemplateColumns: '1fr 0.8fr 1fr 1fr' }}>
              <span className="mono text-sm neutral">{item.date}</span>
              <span className="mono text-sm blue">{item.event}</span>
              <span className="mono text-sm gold">
                {item.level ? Number(item.level).toFixed(2) : item.zoneLow ? `${Number(item.zoneLow).toFixed(2)} - ${Number(item.zoneHigh).toFixed(2)}` : 'N/A'}
              </span>
              <span className="mono text-sm neutral">{item.zoneLow ? 'Projection zone trigger' : 'Projection level trigger'}</span>
            </div>
          ))}
          {!modelReplay?.replayEvents?.length && (
            <div className="h-full flex items-center justify-center p-8 text-center">
              <p className="spark-note">Run model replay to inspect projection-aware entries, targets, and invalidations.</p>
            </div>
          )}
        </div>
      </section>
    </main>
  );
}

function Metric({ label, value, tone }) {
  return (
    <div className="summary-card">
      <div className="summary-label">{label}</div>
      <div className={`summary-value ${tone}`}>{value}</div>
    </div>
  );
}

function toneForAction(action) {
  if (action === 'BUY') return 'positive';
  if (action === 'SELL') return 'negative';
  return 'gold';
}
