global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: alphatrade-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - order-gateway:8081
          - risk-svc:8082
          - match-engine:8083
          - portfolio-svc:8084
          - api-gateway:8085
          - market-data-svc:8087
          - analysis-svc:8088
          - backtest-svc:8089
